package inventaire.domain;
// Generated 7 janv. 2013 21:12:29 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="PRODUCTS"
    ,schema="ROOT"
)
public class Product  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private String quantity;
     private String price;
     private String supplier;

    public Product() {
    }
    public Product(int id){
        this.id = id;
        this.name="";
        this.description="";
        this.quantity="";
        this.price="";
        this.supplier="";
    }
	
    public Product(int id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;
    }
    public Product(int id, String name, String description, String quantity, String price, String supplier) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.quantity = quantity;
       this.price = price;
       this.supplier = supplier;
    }
        public Product( String name, String description, String quantity, String price, String supplier) {
       this.id= -1;
       this.name = name;
       this.description = description;
       this.quantity = quantity;
       this.price = price;
       this.supplier = supplier;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="NAME", nullable=false, length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=25)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="QUANTITY", length=25)
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    
    @Column(name="PRICE", length=25)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    
    @Column(name="SUPPLIER", length=25)
    public String getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }




}


